version: "1.0"
info:
  model: int-scaffold
packages:
- name: NL_ENX_DEMOProject
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/NL_ENX_DEMOProject
  gitUsername: elpinjo
  gitBranch: main
